# SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
# Copyright 2024-2025 NXP

ccflags-y := $(MODULE_CFLAGS)
obj-m += igb_uio/igb_uio.o
obj-m += kpage_ncache/kpage_ncache.o
obj-m += enetc4_uio/enetc4_uio.o
