# SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0)
# Copyright 2024-2026 NXP

ifneq ($(LSXINIC_BUILD),)
DPDKDIR ?= /usr/include/dpdk
MODULE_CFLAGS += -I${DPDKDIR}/drivers/net/lsxinic
endif

ccflags-y := $(MODULE_CFLAGS)
obj-m += igb_uio/igb_uio.o
obj-m += kpage_ncache/kpage_ncache.o
obj-m += enetc4_uio/enetc4_uio.o
obj-m += user_resv_mem/user_resv_mem.o
ifneq ($(LSXINIC_BUILD),)
obj-m += lsxinic/lsinic_kmod.o
endif
